In [25]:
# !pip install nba_api
import json
import pandas as pd
import numpy as np
from nba_api.stats.endpoints import shotchartdetail,playergamelog,leaguestandings
from nba_api.stats.static import players , teams

## Load the Players IDs

In [2]:
# nba_api/stats/static/players.py
list_players=players.get_active_players()
# list_players

In [3]:
df_players=pd.DataFrame(list_players)

In [4]:
players_ids = [item['id'] for item in list_players]
# players_ids

In [5]:
df_players.to_csv('NBA_Players.csv',index=False)

## Load the Team IDs

In [8]:
# nba_api/stats/static/players.py
df_teams=pd.DataFrame(teams.get_teams())

In [9]:
df_teams.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Atlanta,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

In [10]:
df_teams.to_csv('NBA_Teams.csv',index=False)

## Load Shooting Data

In [11]:
#For all active players
for ID in players_ids:
    response = shotchartdetail.ShotChartDetail(
        team_id=0,
        player_id=ID,
        season_nullable='2021-22',
        season_type_all_star='Regular Season',
        context_measure_simple='FGA'
    )
    content = json.loads(response.get_json())
    
    # transform contents into dataframe
    if(ID==players_ids[0]):
        results = content['resultSets'][0]
        headers = results['headers']
        rows = results['rowSet']
        df_active_players = pd.DataFrame(rows)
        df_active_players.columns = headers
    else:
        results = content['resultSets'][0]
        rows = results['rowSet']
        if(len(rows)==0):
            continue
        df = pd.DataFrame(rows)
        df.columns = headers
        df_active_players=pd.concat([df_active_players,df])

In [12]:
df_active_players

,GRID_TYPE,GAME_ID,GAME_EVENT_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_NAME,PERIOD,MINUTES_REMAINING,SECONDS_REMAINING,...,SHOT_ZONE_AREA,SHOT_ZONE_RANGE,SHOT_DISTANCE,LOC_X,LOC_Y,SHOT_ATTEMPTED_FLAG,SHOT_MADE_FLAG,GAME_DATE,HTM,VTM
0,Shot Chart Detail,0022100006,14,1630173,Precious Achiuwa,1610612761,Toronto Raptors,1,10,37,...,Center(C),Less Than 8 ft.,2,-17,13,1,0,20211020,TOR,WAS
1,Shot Chart Detail,0022100006,28,1630173,Precious Achiuwa,1610612761,Toronto Raptors,1,9,29,...,Center(C),Less Than 8 ft.,1,10,-3,1,0,20211020,TOR,WAS
2,Shot Chart Detail,0022100006,33,1630173,Precious Achiuwa,1610612761,Toronto Raptors,1,9,1,...,Center(C),Less Than 8 ft.,0,5,0,1,1,20211020,TOR,WAS
3,Shot Chart Detail,0022100006,45,1630173,Precious Achiuwa,1610612761,Toronto Raptors,1,7,51,...,Center(C),Less Than 8 ft.,0,-5,7,1,0,20211020,TOR,WAS
4,Shot Chart Detail,0022100006,231,1630173,Precious Achiuwa,1610612761,Toronto Raptors,2,8,34,...,Center(C),Less Than 8 ft.,0,0,0,1,0,20211020,TOR,WAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,Shot Chart Detail,0022101222,236,1627826,Ivica Zubac,1610612746,LA Clippers,2,4,47,...,Center(C),Less Than 8 ft.,0,0,0,1,1,20220410,LAC,OKC
491,Shot Chart Detail,0022101222,251,1627826,Ivica Zubac,1610612746,LA Clippers,2,3,11,...,Center(C),Less Than 8 ft.,6,-16,61,1,1,20220410,LAC,OKC
492,Shot Chart Detail,0022101222,263,1627826,Ivica Zubac,1610612746,LA Clippers,2,2,9,...,Center(C),Less Than 8 ft.,4,18,37,1,0,20220410,LAC,OKC
493,Shot Chart Detail,0022101222,282,1627826,Ivica Zubac,1610612746,LA Clippers,2,0,49,...,Center(C),Less Than 8 ft.,0,0,0,1,1,20220410,LAC,OKC
494,Shot Chart Detail,0022101222,328,1627826,Ivica Zubac,1610612746,LA Clippers,3,8,47,...,Center(C),Less Than 8 ft.,5,2,55,1,1,20220410,LAC,OKC

In [13]:
df_active_players.to_csv('NBA_Active_Players_Data_14-04-2022.csv',index=False)

## Load PLayers Stats

In [14]:
#For all active players
for ID in players_ids:
    response = playergamelog.PlayerGameLog(
        player_id=ID,
        season='2021-22',
        season_type_all_star='Regular Season'
    )
    content = json.loads(response.get_json())
    
    # transform contents into dataframe
    if(ID==players_ids[0]):
        results = content['resultSets'][0]
        headers = results['headers']
        rows = results['rowSet']
        df_players_stats = pd.DataFrame(rows)
        df_players_stats.columns = headers
    else:
        results = content['resultSets'][0]
        rows = results['rowSet']
        if(len(rows)==0):
            continue
        df = pd.DataFrame(rows)
        df.columns = headers
        df_players_stats=pd.concat([df_players_stats,df])

In [15]:
df_players_stats

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22021,1630173,0022101226,"APR 10, 2022",TOR @ NYK,L,26,4,13,0.308,...,4,6,2,1,1,1,2,9,-7,1
1,22021,1630173,0022101206,"APR 08, 2022",TOR vs. HOU,W,12,2,5,0.400,...,1,1,0,0,1,2,2,8,-28,1
2,22021,1630173,0022101197,"APR 07, 2022",TOR vs. PHI,W,40,7,11,0.636,...,3,4,2,1,1,5,1,20,5,1
3,22021,1630173,0022101182,"APR 05, 2022",TOR vs. ATL,W,24,4,11,0.364,...,1,2,0,1,0,0,1,11,21,1
4,22021,1630173,0022101172,"APR 03, 2022",TOR vs. MIA,L,21,1,4,0.250,...,2,2,1,0,0,1,2,3,-2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,22021,1627826,0022100076,"OCT 29, 2021",LAC @ POR,L,22,1,5,0.200,...,3,5,1,0,2,1,2,3,-16,1
72,22021,1627826,0022100064,"OCT 27, 2021",LAC vs. CLE,L,24,4,6,0.667,...,2,4,1,0,1,0,3,11,-8,1
73,22021,1627826,0022100049,"OCT 25, 2021",LAC vs. POR,W,25,5,6,0.833,...,8,8,4,2,0,1,0,10,14,1
74,22021,1627826,0022100034,"OCT 23, 2021",LAC vs. MEM,L,19,3,7,0.429,...,4,8,3,0,0,0,2,6,-18,1
75,22021,1627826,0022100016,"OCT 21, 2021",LAC @ GSW,L,17,4,7,0.571,...,2,3,2,0,0,0,2,14,-14,1

In [16]:
df_players_stats.to_csv('NBA_Players_Stats_Data_14-04-2022.csv',index=False)

## Load Season Standindgs

In [31]:

response = leaguestandings.LeagueStandings(
    league_id='00',
    season='2021-22',
    season_type='Regular Season'
)

content = json.loads(response.get_json())

In [42]:
# transform contents into dataframe
results = content['resultSets'][0]
headers = results['headers']
rows = results['rowSet']
teams_standings = pd.DataFrame(rows)
teams_standings.columns = headers

In [43]:
teams_standings.head()

,LeagueID,SeasonID,TeamID,TeamCity,TeamName,Conference,ConferenceRecord,PlayoffRank,ClinchIndicator,Division,...,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,PreAS,PostAS
0,00,22021,1610612756,Phoenix,Suns,West,39-13,1,- w,Pacific,...,None,None,None,None,None,2-3,16-0,9-5,48-10,16-8
1,00,22021,1610612748,Miami,Heat,East,35-17,1,- e,Southeast,...,None,None,None,None,None,5-1,8-7,10-5,38-21,15-8
2,00,22021,1610612738,Boston,Celtics,East,33-19,2,- a,Atlantic,...,None,None,None,None,None,2-4,9-6,6-9,34-26,17-5
3,00,22021,1610612763,Memphis,Grizzlies,West,36-16,2,- sw,Southwest,...,None,None,None,None,None,3-3,8-7,12-4,41-19,15-7
4,00,22021,1610612744,Golden State,Warriors,West,33-19,3,- x,Pacific,...,None,None,None,None,None,5-1,13-2,9-4,42-17,11-12

In [44]:
teams_standings.to_csv('NBA_Season_Team_Standings.csv',index=False)